# Generated by Django 4.0.4 on 2022-07-25 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exifApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='UploadImage',
        ),
    ]
