# Generated by Django 4.0.4 on 2022-07-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exifApp', '0003_uploadimage_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='name',
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
