# Generated by Django 4.0.4 on 2022-07-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exifApp', '0004_remove_uploadimage_name_uploadimage_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadimage',
            old_name='file',
            new_name='upload_file',
        ),
    ]
