# Generated by Django 4.0.6 on 2022-08-06 12:46

from django.db import migrations
import exiffield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exifApp', '0006_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='exif',
            field=exiffield.fields.ExifField(default={}, editable=False),
        ),
    ]
