# Generated by Django 4.0.6 on 2022-08-06 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exifApp.filechecker
import exifApp.models
import exiffield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exifApp', '0007_uploadimage_exif'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', exifApp.filechecker.ContentTypeRestrictedFileField(upload_to=exifApp.models.user_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exif', exiffield.fields.ExifField(default={}, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadImage',
        ),
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
