# Generated by Django 4.0.6 on 2022-08-06 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exifApp.filechecker
import exifApp.models
import exifApp.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exifApp', '0009_remove_fileupload_created_at_fileupload_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=exifApp.filechecker.ContentTypeRestrictedFileField(upload_to=exifApp.models.user_directory_path, validators=[exifApp.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_file'),
        ),
    ]
